### ISSUE TITLE
Got the issue for using tool

### ISSUE THREAD

**Issue by michaelii** [MShudrak/ida-metrics_static#19]
Hi

I am doing the research with This tool.

I install the plugin in IDApro 6.8  with  Python 2.7  (is good )

I run the IDAmetrics_dynamic .py  (Alt +F7) in IDA

And I choose the a.out which is build by GCC on Linux  (just a hello world program)

I got the error log here

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\Lib\lib-tk\Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "E:/CSE_Lei/IDA/IDAmetrics-master\IDAMetrics_static.py", line 1103, in <lambda>
    command = lambda: self.GetUserChoice(callback)).pack(side=LEFT)
  File "E:/CSE_Lei/IDA/IDAmetrics-master\IDAMetrics_static.py", line 1126, in GetUserChoice
    callback(self.metrics_used)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_dynamic.py", line 284, in prepare
    metrics_dynamic.get_dynamic_metrics(fname, metrics_used)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_dynamic.py", line 165, in get_dynamic_metrics
    self.get_basic_dynamic_metrics(trace, metrics_static, metrics_used)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_dynamic.py", line 85, in get_basic_dynamic_metrics
    instr_addr = int(instr_addr, 0) + self.image_base
ValueError: invalid literal for int() with base 0: '\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00>\x00\x01\x00\x00\x000\x04@\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\xe0\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x008\x00\t\x00@\x00\x1f\x00\x1c\x00\x06\x00\x00\x00\x05\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00@\x00\x00\x00\x00\x00@\x00@\x00\x00\x00\x00\x00\xf8\x01\x00\x00\x00\x00\x00\x00\xf8\x01\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x008\x02\x00\x00\x00\x00\x00\x008\x02@\x00\x00\x00\x00\x008\x02@\x00\x00\x00\x00\x00\x1c\x00\x00\x00\x00\x00\x00\x00\x1c\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\xf4\x06\x00\x00\x00\x00\x00\x00\xf4\x06\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00\x10\x0e\x00\x00\x00\x00\x00\x00\x10\x0e`\x00\x00\x00\x00\x00\x10\x0e`\x00\x00\x00\x00\x00(\x02\x00\x00\x00\x00\x00\x000\x02\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x02\x00\x00\x00\x06\x00\x00\x00(\x0e\x00\x00\x00\x00\x00\x00(\x0e`\x00\x00\x00\x00\x00(\x0e`\x00\x00\x00\x00\x00\xd0\x01\x00\x00\x00\x00\x00\x00\xd0\x01\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00T\x02\x00\x00\x00\x00\x00\x00T\x02@\x00\x00\x00\x00\x00T\x02@\x00\x00\x00\x00\x00D\x00\x00\x00\x00\x00\x00\x00D\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00P\xe5td\x04\x00\x00\x00\xcc\x05\x00\x00\x00\x00\x00\x00\xcc\x05@\x00\x00\x00\x00\x00\xcc\x05@\x00\x00\x00\x00\x004\x00\x00\x00\x00\x00\x00\x004\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00Q\xe5td\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00R\xe5td\x04\x00\x00\x00\x10\x0e\x00\x00\x00\x00\x00\x00\x10\x0e`\x00\x00\x00\x00\x00\x10\x0e`\x00\x00\x00\x00\x00\xf0\x01\x00\x00\x00\x00\x00\x00\xf0\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00/lib64/ld-linux-x86-64.so.2\x00\x04\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00GNU\x00\x00\x00\x00\x00\x02\x00\x00\x00\x06\x00\x00\x00 \x00\x00\x00\x04\x00\x00\x00\x14\x00\x00\x00\x03\x00\x00\x00GNU\x00\x88\xd2"C\x02\xa7\xce2\xc6\xfa\x00\xeb\xfdR\xd9t\xf2\x13&\xa3\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00libc.so.6\x00printf\x00__libc_start_main\x00__gmon_start__\x00GLIBC_2.2.5\x00\x00\x00\x00\x02\x00\x02\x00\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00u'
done

What's this mean? or should I set up any environment for building a.out?

If I got the wrong step, please tell me

Thanks

Michael

**Comment by mxmssh** [comment]
Hi, thank you for your interest. 

The main goal of IDAMetrics dynamic is to calculate complexity of executed trace of a program. So, you need to collect a trace of executed instructions first (e.g. using Intel PIN) and then provide it along with application itself. 

To be able to use IDAMetrics you have to do the following steps:
1. Install IDA + Python environment (done in your case)
2. Open your application in IDA, let IDA finish analysis (it's important).
3. Run IDAMetrics_static or IDAMetrics_dynamic (depends on your goal) (ALT + F7 in IDA)
4. In case of IDAMetrics_dynamic provide a trace of executed instructions.

Probably you need IDAMetrics_static. Anyway I can provide in more details if you can clarify your goal.

**Comment by michaelii** [comment]
Thank you for your quick feedback.

I think I just want to know the question "How many basic block" . I think I should run the static one.

I let IDA finish analysis my hello.exe file (which is build by MinGw(gcc) on windows )

Run IDAMetrics_static  and choose Basic Block Count.  And I got the pop up screen show running python script. 

However, I wait  10mins for the result. It still show please wait.

Is it a normal situation to wait over 15 mins? or the wrong setting.

Thanks

Michael

**Comment by michaelii** [comment]
Update the information
When I click cancel for the running python script. It will show some log.

Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.
Start metrics calculation
Analysing  0x4003c8L
Can't collect metric for this function  0x4003c8L
Skip
Analysing  0x400400L
Can't collect metric for this function  0x400400L
Skip
Analysing  0x400410L
Can't collect metric for this function  0x400410L
Skip
Analysing  0x400420L
Can't collect metric for this function  0x400420L
Skip
Analysing  0x400430L
Can't collect metric for this function  0x400430L
Skip
Analysing  0x400460L
Can't collect metric for this function  0x400460L
Skip
Analysing  0x4004a0L
Can't collect metric for this function  0x4004a0L
Skip
Analysing  0x4004e0L
Can't collect metric for this function  0x4004e0L
Skip
Analysing  0x400500L
Exception KeyboardInterrupt: 'User interrupted' in <bound method area_t.<lambda> of <idaapi.area_t; proxy of <Swig Object of type 'area_t *' at 0x055EDA40> >> ignored
Can't collect metric for this function  0x400500L
Skip
Analysing  0x400526L
Can't collect metric for this function  0x400526L
Skip
Analysing  0x400540L
Can't collect metric for this function  0x400540L
Skip
Analysing  0x4005b0L
Can't collect metric for this function  0x4005b0L
Skip
Analysing  0x4005b4L
Can't collect metric for this function  0x4005b4L
Skip
Analysing  0x601040L
Exception KeyboardInterrupt: 'User interrupted' in <bound method area_t.<lambda> of <idaapi.area_t; proxy of <Swig Object of type 'area_t *' at 0x055ED9E0> >> ignored
Can't collect metric for this function  0x601040L
Skip
Analysing  0x601044L
Exception KeyboardInterrupt: 'User interrupted' in <bound method area_t.<lambda> of <idaapi.area_t; proxy of <Swig Object of type 'area_t *' at 0x055ED758> >> ignored
Can't collect metric for this function  0x601044L
Skip
Analysing  0x601048L
Exception KeyboardInterrupt: 'User interrupted' in <bound method area_t.<lambda> of <idaapi.area_t; proxy of <Swig Object of type 'area_t *' at 0x055ED9E0> >> ignored
Exception KeyboardInterrupt: 'User interrupted' in <bound method func_tail_iterator_t.<lambda> of <idaapi.func_tail_iterator_t; proxy of <Swig Object of type 'func_tail_iterator_t *' at 0x055ED9F8> >> ignored
Can't collect metric for this function  0x601048L
Skip
Analysing  0x60104cL
Can't collect metric for this function  0x60104cL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Can't collect metric for this function  0xffffffffffffffffL
Skip
Analysing  0xffffffffffffffffL
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\Lib\lib-tk\Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_static.py", line 1103, in <lambda>
    command = lambda: self.GetUserChoice(callback)).pack(side=LEFT)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_static.py", line 1126, in GetUserChoice
    callback(self.metrics_used)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_static.py", line 1060, in init_analysis
    metrics_total.start_analysis(metrics_used)
  File "E:/CSE_Lei/IDA/IDAmetrics-master/IDAMetrics_static.py", line 259, in start_analysis
    except:
KeyboardInterrupt: User interrupted
done

Is it mean my exe file is not the formal style ?

Thnkas

Michael

**Comment by mxmssh** [comment]
Hi, no it looks like a bug in IDAMetrics. If you could provide the application you're trying to analyze I will prepare a patch.

**Comment by michaelii** [comment]
[https://drive.google.com/drive/folders/0B_Zxbd3UFErXa2IwUmhOSWFsYkk?usp=sharing](url)
`#include<stdio.h>

int main()
{
	for (int i = 0; i < 100; i++)
    printf ("%d", i);
	return 0;
}`

Hi

Basically, we want to use this tool to analyse the performance of Compiler.
The input should be any c or cpp file.  This is my sample file and exe file.
This is the environment setting

OS: Win7 64bit
IDA: IDA pro 6.8
Python: 2.7 (64bit)
IDApython: 1.7 (64bit)
Output a.exe Compiler : MinGW (gcc 5.3.0)

This is the step from me

1. Import LoopUn.c to IDA ( finish analyse)
2. ALT+F7  select IDAMetrics_static.py
3. choose "Basic Block Count"
4. execute

The system show the running python script and  will show the log of 

Can't collect metric for this function  "address"
The address for example 0x400400L

I do not execute Intel pin.

Please go to the google drive to check the file.

If I got the wrong step or need any information. Please just tell me.

Thanks a lot

Michael

**Comment by mxmssh** [comment]
Are you using IDA 64 bit ? If so, it's not yet supported by IDAMetrics, you could use 32bit IDA instead, since your executable is compiled as 32 bit. The rest seems ok for me.

**Comment by michaelii** [comment]
Cool !! it works. I use the 32bit and rebuild the program again on 32bit mode it works.

Right now, I have several question for this tool

1. If I want to execute the dynamic.py  should I need to do some pre-setting (like run Intel PIN?)
2. The "Line of Code" what's that mean ? it means the original code on C file (but it looks like not)
    e.g. my program only has 6 line but result shows 18
3. Does this tool may support 64bits in the future?

Thanks

Michael

**Comment by mxmssh** [comment]
Hi,
1. Yes you need to run Intel PIN and provide a list of basic blocks that were executed in a program.
2. No, it's machine instructions.
3. Yes, it shouldn't be hard but I'm not currently working on this tool. Contributions are more than welcome :)

**Comment by michaelii** [comment]
Cool

Thank you for your help.

Can you tell me how to use hidden mode? (I already check the code)
I want to use my IDApro on the command line

Thanks

Michael

**Comment by mxmssh** [comment]
Ok, it's not hard:
1. You have to setup the following command line environment variable IDAPYTHON=auto
2. You can run IDA + IDAMetrics using the following command line:
<path_to_ida>\idaq -A -S"<path_to_your_script\IDAMetrics_static.py"  <exe_name>

I can provide concrete example later.

**Comment by mxmssh** [comment]
"C:\Program Files\IDA 6.8\idaq.exe" -A -OIDAPython:"C:\IDAMetrics\IDAmetrics\IDAMetrics_static.py" C:\Users\max\Desktop\Challenge1.exe

**Comment by mxmssh** [comment]
and if you need only basic blocks count, you can just change metrics_mask[i] = 1 to metrics_mask[i] = 0
at line https://github.com/mxmssh/IDAmetrics/blob/master/IDAMetrics_static.py#L1222

**Comment by michaelii** [comment]
Hi

Thank you for your quickly reply.

I will try to test and give you feedback ASAP

Thanks

Michael

**Comment by michaelii** [comment]
Hi

Thank you for your help.

I have further question.

I want to use this script on Linux IDA 6.95.

However, the system always show no module named Tkinter. 

My python is 2.7.9  

Do you know how to fix the issue? I guess specifically in the Linux system.

Thanks

michael

**Comment by mxmssh** [comment]
Well, I think you can try just install tkinter using:
`apt-get install python-tk`

**Comment by michaelii** [comment]
Hi

Yes, It is work on my local system python. But IDApython.

I cannot find the method to make the the default of IDApython's python library on system.

Do you have any material for me to read or modify?

I try whole week still cannot fix.

**Comment by mxmssh** [comment]
looks like something wrong with environment variables, it's hard to say what's exactly incorrect, at least try to setup everything according to:
https://www.tutorialspoint.com/python/python_environment.htm

**Comment by michaelii** [comment]
Hi

Thank you for your respond
We are appreciate this tool which is very useful for our research.
We are start to using in our project.

We are expect the 64bits version. 
I close the issue right now.

Keep in touch 

Michael

**Comment by mxmssh** [comment]
Thank you.

**Comment by strongcourage** [comment]
Thanks @mxmssh for the scripts. 

Hi @michaelii. Can you elaborate how did you install Tkinter for IDA Pro's python ? I face the same problem. Thanks.
